[project]
name = "fastapi-ddd-template"
version = "0.1.0"
description = "this project is a DDD template"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.19.2",
    "fastapi>=0.141.1",
    "logging>=0.4.9.6",
    "psycopg[binary]>=3.3.5",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
    "sqlalchemy>=2.0.52",
    "structlog>=26.1.0",
    "uvicorn>=0.52.4",
]

[dependency-groups]
dev = [
    "mypy>=2.3.1",
    "pytest>=9.1.1",
    "ruff>=0.16.6",
]

[tool.ruff]
line-length = 120
target-version = "py313"
extend-exclude = ["migrations"]

[tool.ruff.lint]
select = ["E", "F", "W", "I", "N", "UP", "B", "A", "SIM", "T20", "ERA",  "ARG", "ANN"]

[tool.ruff.lint.flake8-annotations]
mypy-init-return = true
suppress-none-returning = true

[tool.ruff.lint.per-file-ignores]
"test/**" = ["ANN", "ARG", "T20"]

[tool.mypy]
python_version = "3.13"
files = ["src"]
mypy_path = "."
strict = true

[[tool.mypy.overrides]]
module = "tests.*"
disallow_untyped_defs = false

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.uv.workspace]
members = [
    "alembic",
]
